version: "3"

services:
  go-server:
    image: "gocd/gocd-server:v19.12.0"
    ports:
      - "8153:8153"
    volumes:
      - ./gocd-config:/godata/config
    networks:
      - gocd

  go-agent:
    image: "gocd/gocd-agent-alpine-3.9:v19.12.0"
    environment:
      GO_SERVER_URL: "https://go-server:8154/go"
      AGENT_AUTO_REGISTER_KEY: "verysecurekey"
      AGENT_AUTO_REGISTER_RESOURCES: "${GOCD_AUTO_REGISTER_RESOURCES:-gocd}"
      AGENT_AUTO_REGISTER_HOSTNAME: "go-agent"
      AGENT_AUTO_REGISTER_ENVIRONMENTS: "testing,default"
    networks:
      - gocd

networks:
  gocd:
    driver: bridge
